language: java
  
branches:
  only:
  - master

env:
  global:
    - CI_TOOL=travis

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

jobs:
  include:
  
  - name: build
    language: shell
    script: tools/ci/core/build.sh
    if: env(CI_JOB) IS NOT present OR env(CI_JOB) = build

  - name: server
    before_install: cd apps/server
    script: ./gradlew clean build --no-daemon
    if: env(CI_JOB) = server

  - name: client
    before_install: cd apps/client
    script: ./gradlew clean build --no-daemon
    if: env(CI_JOB) = client
