language: java
  
branches:
  only:
  - master

env:
  global:
    - CI_TOOL=travis

jobs:
  include:
  
  - name: build
    language: shell
    script: travis token
    if: env(CI_JOB) IS NOT present OR env(CI_JOB) = build

  - name: server
    before_install: cd apps/server
    script: ./gradlew clean build
    if: env(CI_JOB) = server

  - name: client
    before_install: cd apps/client
    script: ./gradlew clean build
    if: env(CI_JOB) = client
