language: java
  
branches:
  only:
  - master

jobs:
  include:
  
  - name: build
    script: tools/ci/core/build.sh
    if: type = push

  - name: server
    before_script: cd apps/server
    script: ./gradlew clean build
    if: type = api

  - name: client
    before_script: cd apps/client
    script: ./gradlew clean build
    if: type = api
