image: urbantower/openjdk:8

pipelines:
  default:
    - step:
        script: 
          - bash .circleci/build.sh
  custom:
    server:
      - step:
          name: Build Server
          caches:
            - apps/server/.gradle
          script:
            - cd apps/server
            - ./gradlew clean build
    client:
      - step:
          name: Build Client
          caches:
            - apps/client/.gradle
          script:
            - cd apps/client
            - ./gradlew clean build