image: urbantower/openjdk:8

pipelines:
  branches:      
    master:
     - step:
         script: 
           - bash .circleci/build.sh
  custom:
    server:
      - step:
          name: Build Server
          caches:
            - gradle
          script:
            - cd apps/server
            - ./gradlew clean build
    client:
      - step:
          name: Build Client
          caches:
            - gradle
          script:
            - cd apps/client
            - ./gradlew clean build
