image: openjdk:8

pipelines:
  default:
    - step:
        script: 
          - bash .circleci/build.sh
  custom:
    server:
      - step:
          script:
            - echo "Building server"
    client:
      - step:
          script:
            - echo "Building client"