version: 2.1

orbs:
  compare-url: iynere/compare-url@0.4.5

workflows:
  main:
    jobs:
      - build
  server:
    jobs:
      - server:
          filters:
            tags:
              only: /^server$/

jobs:
  build:
    docker:
      - image: circleci/openjdk:8
    steps:
      - checkout

      - compare-url/reconstruct

      - run:
          name: Trigger build for modified projects
          shell: /bin/bash -exo pipefail
          command: |
            # save value stored in file to a local env var
            CIRCLE_COMPARE_URL=$(cat CIRCLE_COMPARE_URL.txt)
            COMMIT_RANGE=$(echo $CIRCLE_COMPARE_URL | sed 's:^.*/compare/::g')
            echo \"Commit range: $COMMIT_RANGE\"

            for PROJECT in $(.circleci/list-projects.sh); do
              PROJECT_NAME=$(basename $PROJECT)
              if [[ $(git diff $COMMIT_RANGE --name-status | grep "$PROJECT") ]]; then
                echo "Triggering build for $PROJECT"
                curl -X POST  --data tag=$PROJECT_NAME \
                https://circleci.com/api/v1.1/project/github/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/build?circle-token=$CIRCLE_API_USER_TOKEN
              fi
            done

  server:
    docker:
      - image: circleci/openjdk:8
    working_directory: ~/project/apps/server
    steps:
      - checkout
      - run:
          name: Build Server
          command: ./gradlew build
