version: 2

jobs:
  build:
    docker:
      - image: circleci/openjdk:8
    steps:
      - checkout
      - run:
          name: Trigger build for modified projects
          shell: /bin/bash
          command: .circleci/build.sh

  server:
    docker:
      - image: circleci/openjdk:8
    working_directory: ~/project/apps/server
    steps:
      - checkout
      - run:
          name: Build Server
          command: ./gradlew build

  client:
    docker:
      - image: circleci/openjdk:8
    working_directory: ~/project/apps/client
    steps:
      - checkout
      - run:
          name: Build Client
          command: ./gradlew build        

  common:
    docker:
      - image: circleci/openjdk:8
    working_directory: ~/project/libs/common
    steps:
      - checkout
      - run:
          name: Build Common
          command: ./gradlew build      

  logging:
    docker:
      - image: circleci/openjdk:8
    working_directory: ~/project/libs/logging
    steps:
      - checkout
      - run:
          name: Build Logging
          command: ./gradlew build      
