name: main

on: [push]

jobs:
  
  build:
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Run main build runner
        env:
          CI_TOOL: github
        run: tools/ci/core/build.sh