name: projects

on: repository_dispatch

jobs:

  server:
    if: github.event.client_payload.job == 'server'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build Server
        working-directory: ./apps/server
        env:
          CI_TEST: ${{ github.event }}
        run: |
          echo ${CI_TEST}
          ./gradlew clean build